FROM node:24.5.0

WORKDIR /usr/src/app

COPY package*.json nx.json tsconfig.base.json ./

RUN npm ci --legacy-peer-deps

COPY . .

EXPOSE 4200

CMD ["npx", "nx", "serve", "frontend", "--host=0.0.0.0"]