# ---------- Builder ----------
FROM node:20-alpine AS builder
WORKDIR /workspace
RUN apk add --no-cache python3 make g++ libc6-compat
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY . .
RUN npx nx build backend

# ---------- Runner ----------
FROM node:20-alpine AS runner
WORKDIR /workspace
ENV NODE_ENV=production
COPY package*.json ./
COPY --from=builder /workspace/node_modules ./node_modules
RUN npm prune --omit=dev
COPY --from=builder /workspace/dist ./dist
EXPOSE 3000
CMD ["node", "dist/apps/backend/main.js"]